GET http://localhost:4001/posts/1234/comments

#### post call
POST http://localhost:4001/posts/6da26b85/comments
Content-Type: application/json

{
	"content":"Second comment"
}
#### post call
POST http://localhost:4001/events
Content-Type: application/json

{
	"type":"Second comment"
}

